# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d52775bb0cbe196c6cab6e52fccdc3daaa3c59774f1ada00e7afbb84c093d0abce6c509d09efe8ebb4bb4805ebc28154bac37d140c72be1e843109ee8d28d40

test:
  secret_key_base: fc9db47ea340c747c84d7ed18e376fc298d630685cae4df305d21cc679208f392810f1eac8c80f8b4dfcf5c6caefaf589fbbdcefb32645f515306a48c3dbd43c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
